name: my_first_app
description: An image classification app built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.10.0'

dependencies:
  flutter:
    sdk: flutter
  
  image_picker: ^1.0.4 
  tflite_v2: ^1.0.0

  # Firebase packages
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2

  # Charting package
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

# Final, definitive configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/classes/basketball.jpg"
  min_sdk_android: 21 # Required for adaptive icons
  adaptive_icon_background: "#008080"
  adaptive_icon_foreground: "assets/classes/basketball.jpg"


flutter:
  uses-material-design: true
  
  assets:
    - assets/model_unquant.tflite
    - assets/labels.txt
    - assets/classes/
